frontend:
  - changed-files:
      - any-glob-to-any-file: "src/**"

backend:
  - changed-files:
      - any-glob-to-any-file: "src-tauri/**"

documentation:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"

ci/cd:
  - changed-files:
      - any-glob-to-any-file: ".github/**"
